/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import controle.ConexaoBD;

/**
 *
 * @author allan
 */
public class TelaPrincipal extends javax.swing.JFrame {

    ConexaoBD conecta = new ConexaoBD();
    
    public TelaPrincipal() {
        initComponents();
        conecta.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jLabelFundoMenu = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuEquipe = new javax.swing.JMenu();
        jMenuItemEquipeCompleta = new javax.swing.JMenuItem();
        jMenuItemCadastro = new javax.swing.JMenuItem();
        jMenuAnimais = new javax.swing.JMenu();
        jMenuItemAnim = new javax.swing.JMenuItem();
        jMenuItemAçoesAnim = new javax.swing.JMenuItem();
        jMenuPrincSair = new javax.swing.JMenu();
        jMenuItemSairMenuPrinc = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar3.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar4.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar4.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelFundoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundotelamenu.png"))); // NOI18N
        getContentPane().add(jLabelFundoMenu);
        jLabelFundoMenu.setBounds(0, 0, 530, 310);

        jMenuEquipe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeequipe.png"))); // NOI18N
        jMenuEquipe.setText("Equipe");

        jMenuItemEquipeCompleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconefuncionarios.png"))); // NOI18N
        jMenuItemEquipeCompleta.setText("Equipe");
        jMenuItemEquipeCompleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEquipeCompletaActionPerformed(evt);
            }
        });
        jMenuEquipe.add(jMenuItemEquipeCompleta);

        jMenuItemCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconecadastrarusuario.png"))); // NOI18N
        jMenuItemCadastro.setText("Cadastrar membro");
        jMenuItemCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroActionPerformed(evt);
            }
        });
        jMenuEquipe.add(jMenuItemCadastro);

        jMenuBar1.add(jMenuEquipe);

        jMenuAnimais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeanimais.png"))); // NOI18N
        jMenuAnimais.setText("Animais");

        jMenuItemAnim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconetodosanimais.png"))); // NOI18N
        jMenuItemAnim.setText("Ver animais");
        jMenuAnimais.add(jMenuItemAnim);

        jMenuItemAçoesAnim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeações.png"))); // NOI18N
        jMenuItemAçoesAnim.setText("Adicionar nova ação");
        jMenuAnimais.add(jMenuItemAçoesAnim);

        jMenuBar1.add(jMenuAnimais);

        jMenuPrincSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconesair.png"))); // NOI18N
        jMenuPrincSair.setText("Sair");
        jMenuPrincSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPrincSairActionPerformed(evt);
            }
        });

        jMenuItemSairMenuPrinc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconesairpeq.png"))); // NOI18N
        jMenuItemSairMenuPrinc.setText("Sair");
        jMenuItemSairMenuPrinc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairMenuPrincActionPerformed(evt);
            }
        });
        jMenuPrincSair.add(jMenuItemSairMenuPrinc);

        jMenuBar1.add(jMenuPrincSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(526, 399));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuPrincSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPrincSairActionPerformed
        
    }//GEN-LAST:event_jMenuPrincSairActionPerformed

    private void jMenuItemEquipeCompletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEquipeCompletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemEquipeCompletaActionPerformed

    private void jMenuItemCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroActionPerformed
      FormEquipe tela = new FormEquipe();
      tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroActionPerformed

    private void jMenuItemSairMenuPrincActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairMenuPrincActionPerformed
        conecta.desconecta();
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairMenuPrincActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFundoMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenuAnimais;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenu jMenuEquipe;
    private javax.swing.JMenuItem jMenuItemAnim;
    private javax.swing.JMenuItem jMenuItemAçoesAnim;
    private javax.swing.JMenuItem jMenuItemCadastro;
    private javax.swing.JMenuItem jMenuItemEquipeCompleta;
    private javax.swing.JMenuItem jMenuItemSairMenuPrinc;
    private javax.swing.JMenu jMenuPrincSair;
    // End of variables declaration//GEN-END:variables
}
